[package]
name = "gronly"
description = "Concurrent grow-only containers"
readme = "README.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
default = []
alloc = ["allocator-api2/alloc"]
std = ["alloc", "allocator-api2/std"]

[dependencies]
gronly-atomics = { workspace = true }
allocator-api2 = { version = "0.2", default-features = false, features = [] }

[dev-dependencies]
gronly-atomics = { workspace = true, features = ["std", "macros"] }
papaya = "0.2"

[workspace]
resolver = "2"
members = [
    "example-gronly-atomics",
    "gronly-atomics",
    "gronly-atomics-macros",
]

[workspace.package]
authors = ["Joseph Hartsell <me@jahartsell.com>"]
edition = "2021"
license = "MIT or Apache-2.0"
rust-version = "1.65"
version = "0.1.0"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
undocumented-unsafe-blocks = "warn"

[workspace.lints.rust]
missing-docs = "warn"
rust-2024-compatibility = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)', 'cfg(shuttle)'] }

[workspace.dependencies]
gronly = { path = ".", version = "0.1" }
gronly-atomics = { path = "gronly-atomics", version = "0.1" }
gronly-atomics-macros = { path = "gronly-atomics-macros", version = "0.1" }
